[package]
name = "test-framework"
version = "1.0.0"
authors = ["T-Force Xyz"]
license = "Apache-2.0"
edition = "2021"

[dependencies]
anchor-lang = "0.24.2"
solana-program = "1.9.29"

[dev-dependencies]
arrayref = "0.3.6"
num_enum = "0.5.4"
solana-cli-config = "1.9.29"
solana-program-test = "1.9.29"
solana-sdk = "1.9.29"
tokio = "1.14.1"

[features]
cpi = ["no-entrypoint"]
default = []
localhost = []
no-entrypoint = []
no-idl = []

[lib]
name = "test_framework"
crate-type = ["cdylib", "lib"]
