[package]
name = "test-framework"
version = "1.0.0"
authors = ["T-Force Xyz"]
license = "Apache-2.0"
edition = "2021"

[dependencies]
anchor-lang = "0.24.2"
solana-program = "1.9.29"

[dev-dependencies]
anchor-client = "0.24.2"
env_logger="0.9.0"
solana-cli-config = "1.9.29"
solana-program-test = "1.9.29"
solana-sdk = "1.9.29"
rand = "0.8.5"
spl-token = "3.2.0"
spl-associated-token-account = "1.0.0"
tokio = "1.14.1"

[features]
cpi = ["no-entrypoint"]
default = []
no-entrypoint = []
no-idl = []

[lib]
name = "test_framework"
crate-type = ["cdylib", "lib"]
